language: php
php:
  - 7.3
script: bash ./_build/syntaxTest.sh
deploy:
  provider: pages
  local_dir: _build/output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
